# Generated by Django 5.0.6 on 2024-06-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_note_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='ToDo',
        ),
        migrations.AlterModelTable(
            name='todo',
            table='ToDO',
        ),
    ]
